#include <iostream>

using namespace std;

/*
	Project Euler #2 - Even Fibonacci numbers

	Each new term in the Fibonacci sequence is generated by adding the previous
	two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not
	exceed four million, find the sum of the even-valued terms.
*/

main()
{
	const unsigned int limit = 4000000;

	unsigned int fibBase = 1;
	unsigned int fib = 2;

	unsigned int newFib;
 
	unsigned int sum = 0;

	while(fibBase < limit)
	{
		if(fibBase % 2 == 0)
			sum += fibBase;

		newFib = fibBase + fib;

		fibBase = fib;
		fib = newFib;
	}

	cout << sum << endl;

	return 0;
}