#include <string>

using namespace std;

namespace euler
{
    namespace problems
    {
        class Problem002 : public IProblem
        {
        public:
            bool IsProblemSolved()
            {
                return _isProblemSolved;
            }

            uint32_t GetProblemNumber()
            {
                return 2;
            }

            string GetProblemDescription()
            {
                return
                    "Project Euler #2 - Even Fibonacci Numbers"
                    "\n\n"
                    "Each new term in the Fibonacci sequence is generated by "
                    "adding the previous "
                    "two terms.By starting with 1 and 2, the first 10 terms "
                    "will be:"
                    "\n\n"
                    "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..."
                    "\n\n"
                    "By considering the terms in the Fibonacci sequence whose"
                    "values do not exceed four million, find the sum of "
                    "the even-valued terms.";
            }

            void SolveProblem()
            {
                const uint32_t limit = 4000000;

                uint32_t fibBase = 1;
                uint32_t fib = 2;

                uint32_t newFib;

                uint32_t sum = 0;

                while (fibBase < limit)
                {
                    if (fibBase % 2 == 0)
                        sum += fibBase;

                    newFib = fibBase + fib;

                    fibBase = fib;
                    fib = newFib;
                }

                _computedAnswer = sum;
                _isProblemSolved = true;
            }

            string GetComputedAnswer()
            {
                return to_string(_computedAnswer);
            }

            string GetCorrectAnswer()
            {
                return to_string(_correctAnswer);
            }

        private:
            bool _isProblemSolved = false;
            uint32_t _computedAnswer;
            uint32_t _correctAnswer = 4613732;
        };
    }
}
