# This Makefile will be overly documented to provide a reference to GNU Make
# (myself being new to C++ and Make) and to assist others who may wish to learn 
# from this project.

# CC tells Make to use the specified compiler for this project (g++ in this 
# case).

CC=g++

# CFLAGS is a list of parameters to pass to the compiler.
# 
# -c tells g++ to compile specified files, but not to link them.
#
# -Wall tells g++ to display all compiler warnings.

CFLAGS=-Wall